# hint.pbtxt is a config file for xpytest.
#
# Proto type: xpytest.proto.HintFile
# https://github.com/chainer/xpytest/blob/master/proto/test_case.proto

# Slow tests take 60+ seconds.
rules { name: "chainer_tests\\distributions_tests\\test_bernoulli.py" deadline: 240 }
rules { name: "chainer_tests\\functions_tests\\array_tests\\test_cast.py" deadline: 240 }
rules { name: "chainer_tests\\functions_tests\\loss_tests\\test_softmax_cross_entropy.py" deadline: 480 }
rules { name: "chainer_tests\\functions_tests\\math_tests\\test_sparse_matmul.py" deadline: 240 }
rules { name: "chainer_tests\\functions_tests\\normalization_tests\\test_batch_normalization.py" deadline: 240 }
rules { name: "chainer_tests\\functions_tests\\pooling_tests\\test_average_pooling_nd.py" deadline: 240 }
rules { name: "chainer_tests\\optimizers_tests\\test_optimizers_by_linear_model.py" deadline: 240 }

# Slow tests take 10+ seconds.
rules { name: "chainer_tests\\iterators_tests\\test_multiprocess_iterator.py" }
