from chainer.functions.connection import bilinear  # NOQA
from chainer.functions.connection import convolution_2d  # NOQA
from chainer.functions.connection import convolution_nd  # NOQA
from chainer.functions.connection import deconvolution_2d  # NOQA
from chainer.functions.connection import deconvolution_nd  # NOQA
from chainer.functions.connection import depthwise_convolution_2d  # NOQA
from chainer.functions.connection import dilated_convolution_2d  # NOQA
from chainer.functions.connection import embed_id  # NOQA
from chainer.functions.connection import linear  # NOQA
from chainer.functions.connection import n_step_gru  # NOQA
from chainer.functions.connection import n_step_lstm  # NOQA
from chainer.functions.connection import n_step_rnn  # NOQA
from chainer.functions.connection import shift  # NOQA
