from chainer.functions.pooling import average_pooling_2d  # NOQA
from chainer.functions.pooling import average_pooling_nd  # NOQA
from chainer.functions.pooling import average_pooling_nd_kernel  # NOQA
from chainer.functions.pooling import max_pooling_2d  # NOQA
from chainer.functions.pooling import max_pooling_nd  # NOQA
from chainer.functions.pooling import max_pooling_nd_kernel  # NOQA
from chainer.functions.pooling import pooling_2d  # NOQA
from chainer.functions.pooling import pooling_nd  # NOQA
from chainer.functions.pooling import pooling_nd_kernel  # NOQA
from chainer.functions.pooling import roi_pooling_2d  # NOQA
from chainer.functions.pooling import spatial_pyramid_pooling_2d  # NOQA
from chainer.functions.pooling import unpooling_2d  # NOQA
from chainer.functions.pooling import unpooling_nd  # NOQA
from chainer.functions.pooling import upsampling_2d  # NOQA
